# Generated by Django 6.1 on 2026-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Toys', 'Toys'), ('Kids', 'Kids')], default='Clothes', max_length=100),
        ),
    ]
